/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jd522_sa;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liyam
 */
public class Faculty extends javax.swing.JFrame {
    private Connection con;
    private PreparedStatement ps;
    private ResultSet rs;
private DefaultTableModel  tableModel;

    /**
     * Creates new form Faculty
     */
    public Faculty() {
        initComponents();
        con = MyConnection.connectionDB();

        tableModel = (DefaultTableModel) jTable1.getModel();
    }
private void UpdateFaculty(){
        String query = "SELECT * FROM Faculty";
        try {
           ps = con.prepareStatement(query); 
            rs = ps.executeQuery();

            // Clear what's in the table
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }
            // Add information to the JTable
            while (rs.next()) {
                Object[] row = {
                     rs.getString("faculty_id"),
                    rs.getString("first_name"),
                    rs.getString("last_name"),
                    rs.getString("course_id"),
                    rs.getString("course_name"),
                    rs.getString("grades"),
                    rs.getString("enrolled_students"),
                    rs.getString("department_id"),
                };
                tableModel.addRow(row);
            }
            rs.close();  // Close the result set
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
       }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDepId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        txtcourse = new javax.swing.JTextField();
        txtcname = new javax.swing.JTextField();
        txtfID = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtgrades = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtenrolleds1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Faculty management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 56, 170, 30));

        jButton4.setBackground(new java.awt.Color(255, 255, 153));
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 153));
        jButton5.setText("Update");

        jButton7.setBackground(new java.awt.Color(255, 255, 153));
        jButton7.setText("Save");

        jButton8.setBackground(new java.awt.Color(255, 255, 153));
        jButton8.setText("back");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jButton5)
                    .addComponent(jButton4)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(53, 53, 53)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 103, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Faculty ID", "First_name", " last_name", "Course_id", "course_name", "Grades", "Enrolled Students", "Department ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 669, 202));

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        jButton2.setText("Department");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Students");

        jButton1.setText("Courses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel2.setText("Faculty ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        txtDepId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtDepId, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 300, 80, 20));

        jLabel3.setText("Enrolled Students");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, -1));

        jLabel4.setText("First name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, -1, -1));

        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 70, -1));

        jLabel6.setText("Course id");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        jLabel7.setText("Course_name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, -1, -1));
        getContentPane().add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 90, 20));
        getContentPane().add(txtcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 90, 20));
        getContentPane().add(txtcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 90, 20));
        getContentPane().add(txtfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 90, 20));
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 90, 20));

        jLabel8.setText("Grades");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, -1, -1));
        getContentPane().add(txtgrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 90, 20));

        jLabel9.setText("Department ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 100, -1));

        txtenrolleds1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenrolleds1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtenrolleds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 80, 20));

        jButton9.setText("Dashboard");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 220, 320));

        jLabel10.setText("Search");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 60, -1));
        getContentPane().add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 140, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 153));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Department_page dpage = new Department_page();
        dpage.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      try{   String insertQuery = "INSERT INTO faculty (faculty_id, first_name, last_name, course_id, course_name,  grades, enrolled_students, department_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
    ps = con.prepareStatement(insertQuery);
    ps.setString(1, txtfID.getText());
    ps.setString(2, txtfname.getText());
    ps.setString(3, txtlastname.getText());
    ps.setString(4, txtcourse.getText());
    ps.setString(5, txtcname.getText());
    ps.setString(6, txtgrades.getText());
    ps.setString(7, txtDepId.getText());
    ps.setString(8, txtDepId.getText());

    ps.execute();
    JOptionPane.showConfirmDialog(rootPane, "Saved successfully to Database");

} catch (Exception e) {
    JOptionPane.showConfirmDialog(rootPane, "Not saved to DB!");
    e.printStackTrace();
}

       UpdateFaculty();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtDepIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepIdActionPerformed

    private void txtenrolleds1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenrolleds1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenrolleds1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       Homepage_ResourceManagementApp hrpage = new Homepage_ResourceManagementApp();
       hrpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     // Get the text from the search text field
    String searchText = searchTextField.getText();
    
    // Connect to your SQL database
    try {
      
        // Create a SQL DELETE statement based on the search text
        String deleteQuery = "DELETE FROM faculty WHERE Faculty_id = ?";
        
        // Prepare the statement
        PreparedStatement pst = con.prepareStatement(deleteQuery);
        
        // Set the parameter(s) in the statement
        pst.setString(1, searchText);
        
        // Execute the delete statement
        int rowsAffected = pst.executeUpdate();
        
        // Check the result
        if (rowsAffected > 0) {
            // Deletion successful
            JOptionPane.showMessageDialog(null, "Item deleted successfully.");
        } else {
            // Deletion failed
            JOptionPane.showMessageDialog(null, "Failed to delete item.");
        }
        
        // Close the connection and statement
        pst.close();
        con.close();
    } catch (SQLException ex) {
        // Handle any exceptions
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTextField txtDepId;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtcourse;
    private javax.swing.JTextField txtenrolleds1;
    private javax.swing.JTextField txtfID;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgrades;
    private javax.swing.JTextField txtlastname;
    // End of variables declaration//GEN-END:variables
}
